name: Modelops deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]
jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: python version
      run: python --version
    - name: pip install
      run: pip install -r requirements.txt
    - name: train model
      run: python model/train.py
    - name: docker build
      run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}} .
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: docker Push
      run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{ github.sha }}
    - name: update docker user in k8 
      run: sed -i 's/{docker_user}/${{secrets.DOCKER_USER}}/g' manifests/k8s.yml
    - name: update model name in k8 
      run: sed -i 's/{model_name}/${{secrets.MODEL_NAME}}/g' manifests/k8s.yml
    - name: update _ by - 
      run: sed -i 's/_/-/g' manifests/k8s.yml
    - name: update sha in k8
      run: sed -i 's/{github.sha}/${{ github.sha }}/g' manifests/k8s.yml
    - name: show k8s.yml 
      run: cat manifests/k8s.yml
    
